name: Infra

on:
  push:
    paths:
    - '**.tf'
    - '**.hcl'
    - '.github/workflows/infra.yml'

jobs:
  terraform-lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: 'Terraform Format'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.12.24
        tf_actions_subcommand: 'fmt'
        tf_actions_working_dir: './infra/terraform'